apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-injector
  labels:
    app: user-injector
rules:
- apiGroups:
  - genos.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  - virtualmachines
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - autoscaling
  resources:
  - '*'
  verbs:
  - '*'