kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-injector
  labels:
    app: user-injector
subjects:
- kind: ServiceAccount
  name: user-injectort
  namespace: pipeline-infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user-injector